package com.konsol.divinesign.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestAllPropertiesEquals(Request expected, Request actual) {
        assertRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestAllUpdatablePropertiesEquals(Request expected, Request actual) {
        assertRequestUpdatableFieldsEquals(expected, actual);
        assertRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestAutoGeneratedPropertiesEquals(Request expected, Request actual) {
        assertThat(expected)
            .as("Verify Request auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestUpdatableFieldsEquals(Request expected, Request actual) {
        assertThat(expected)
            .as("Verify Request relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getVerified()).as("check verified").isEqualTo(actual.getVerified()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestUpdatableRelationshipsEquals(Request expected, Request actual) {
        assertThat(expected)
            .as("Verify Request relationships")
            .satisfies(e -> assertThat(e.getSplend()).as("check splend").isEqualTo(actual.getSplend()));
    }
}
