package com.konsol.divinesign.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SurahAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurahAllPropertiesEquals(Surah expected, Surah actual) {
        assertSurahAutoGeneratedPropertiesEquals(expected, actual);
        assertSurahAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurahAllUpdatablePropertiesEquals(Surah expected, Surah actual) {
        assertSurahUpdatableFieldsEquals(expected, actual);
        assertSurahUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurahAutoGeneratedPropertiesEquals(Surah expected, Surah actual) {
        assertThat(expected)
            .as("Verify Surah auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurahUpdatableFieldsEquals(Surah expected, Surah actual) {
        assertThat(expected)
            .as("Verify Surah relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getTransliteration()).as("check transliteration").isEqualTo(actual.getTransliteration()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getTotalVerses()).as("check totalVerses").isEqualTo(actual.getTotalVerses()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurahUpdatableRelationshipsEquals(Surah expected, Surah actual) {
        // empty method
    }
}
