package com.konsol.divinesign.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerseAllPropertiesEquals(Verse expected, Verse actual) {
        assertVerseAutoGeneratedPropertiesEquals(expected, actual);
        assertVerseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerseAllUpdatablePropertiesEquals(Verse expected, Verse actual) {
        assertVerseUpdatableFieldsEquals(expected, actual);
        assertVerseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerseAutoGeneratedPropertiesEquals(Verse expected, Verse actual) {
        assertThat(expected)
            .as("Verify Verse auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerseUpdatableFieldsEquals(Verse expected, Verse actual) {
        assertThat(expected)
            .as("Verify Verse relevant properties")
            .satisfies(e -> assertThat(e.getVerse()).as("check verse").isEqualTo(actual.getVerse()))
            .satisfies(e -> assertThat(e.getDiacriticVerse()).as("check diacriticVerse").isEqualTo(actual.getDiacriticVerse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerseUpdatableRelationshipsEquals(Verse expected, Verse actual) {
        assertThat(expected)
            .as("Verify Verse relationships")
            .satisfies(e -> assertThat(e.getSurah()).as("check surah").isEqualTo(actual.getSurah()))
            .satisfies(e -> assertThat(e.getSplendVerses()).as("check splendVerses").isEqualTo(actual.getSplendVerses()));
    }
}
